---


- name: Install Varnish package
  become: yes
  apt:
    pkg: varnish
    update_cache: yes
  when: varnish_enabled
  tags:
    - varnish

- name: Configure Varnish
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: default.vcl.j2, dest: /etc/varnish/default.vcl }
    - { src: varnish.j2, dest: /etc/default/varnish }
  when: varnish_enabled
  notify: restart varnish
  tags:
    - vanish