---


- name: Install Varnish package
  become: yes
  apt:
    pkg: varnish
    update_cache: yes
  when: varnish_enabled
  tags:
    - varnish

- name: Ensure directories exist
  become: yes
  file:
    path: /etc/systemd/system/varnish.service.d
    state: directory
    mode: 0755
  tags:
    - varnish

- name: Configure Varnish
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: default.vcl.j2, dest: /etc/varnish/default.vcl }
    - { src: varnish.j2, dest: /etc/default/varnish }
    - { src: customexec.conf.j2, dest: /etc/systemd/system/varnish.service.d/customexec.conf }
  when: varnish_enabled
  notify: restart varnish
  tags:
    - varnish

- name: Reload Systemd Daemon and restart Varnish
  become: yes
  systemd:
    name: varnish
    state: reloaded
    daemon_reload: yes
  changed_when: false
  tags:
    - varnish